# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DevFriends' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevFriends
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'FirebaseStorage'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'

  target 'DevFriendsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DevFriendsUITests' do
    # Pods for testing
  end

end